---

env: local
log: /var/log/wfsync.log
location: UTC
file_path: /local/file/path
listen:
  bind_ip: 0.0.0.0
  port: 8080
stripe:
  test_mode: true
  api_key: your-stripe-api-key
  test_key: your-test-api-key
  webhook_secret: your-stripe-webhook-secret
wfirma:
  access_key: your-wfirma-access-key
  secret_key: your-wfirma-secret-key
  app_id: your-wfirma-app-id
mongo:
  enabled: false
  host: 127.0.0.1
  port: 27017
  user: admin
  password: pass
  database: evsys
  save_url: mongodb://admin:pass@
opencart:
  enabled: false
  driver: mysql
  hostname: localhost
  username: user
  password: pass
  database: oc
  port: 3306
  prefix: oc_
  file_url: file-url
  status_url_request: 0
  status_url_result: 0
  status_proforma_request: 0
  status_proforma_result: 0
telegram:
  enabled: true
  api_key: your-telegram-api-key